export type {
  ActionType,
  ApplicationContext,
  Assertion,
  AssertionKind,
  BusinessFailureSignal,
  Capability,
  CapabilityMetadata,
  Checkpoint,
  ExpectedOutput,
  ExtractMethod,
  ExtractSpec,
  FailureClass,
  Locator,
  LocatorStrategy,
  OutputType,
  OutputValues,
  ParameterDef,
  ParameterType,
  ParameterValues,
  Step,
  StepInput,
  StepInputSource,
  Target,
  WaitKind,
  WaitSpec,
} from "./capability.js";
export { CAPABILITY_SCHEMA_VERSION, capabilitySchema } from "./capability.js";
export {
  BusinessFailure,
  HardFailure,
  ReplayError,
  SafetyViolation,
  ValidationFailure,
  isBusinessFailure,
  isHardFailure,
  isSafetyViolation,
  isValidationFailure,
} from "./errors.js";
export { formatValidationIssues, loadCapabilityFile, validateCapability } from "./validate.js";
